### ISSUE TITLE
Multiple fallback configurations

### ISSUE THREAD

**Issue by botsvik** [unjs/fontaine#522]
### 🆒 Your use case

Need to be able to configure fallbacks for multiple typefaces.
```css
:root {
  --font-sans: "Geist", "Geist fallback";
  --font-mono: "JetBrains Mono", "JetBrains Mono fallback";
}
```

Currently there is only one `fallbacks` configuration.

### 🆕 The solution you'd like

Configuring `fallbacks` with an object literal would be nice. Maybe accept `string[] | Record<string, string[]>` where key would be font name.
```
fallbacks: {
  Geist: ["BlinkMacSystemFont", "Segoe UI", "Helvetica Neue", "Arial", "Noto Sans"],
  "JetBrains Mono": ["SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"]
}
```

### 🔍 Alternatives you've considered

Have considered using second `FontaineTransform.vite` plugin, with `skipFontFaceGeneration`.
