### ISSUE TITLE
Does not work with Tailwind (or with CSS variables)

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/fontaine#549]
### 🐛 The bug

I have the following css for Tailwind CSS 4:

```css
@theme {
    --font-sans: 'DM Sans', sans-serif;
    --font-sofia: 'Sofia sans', sans-serif;
    --font-mono: 'DM Mono', monospace;
}
```

and it does not work. With the following code:

```css
.google-font {
  font-family: "Poppins", sans-serif;
}

```

### 🛠️ To reproduce

https://github.com/Barbapapazes/fontaine-fork/commit/3379c57ac84f027802deaea471c36a6b22aea8ed

### 🌈 Expected behaviour

It should work with a CSS variable as it works with `font-familly`
